apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: driscoll-golang-template
  name: svc-driscoll-golang-template
spec:
  ports:
  - name: 8000-443
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: driscoll-golang-template
  type: NodePort
status:
  loadBalancer: {}
