apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: driscoll-react-template
  name: svc-driscoll-react-template
spec:
  ports:
  - name: 3000-443
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: driscoll-react-template
  type: NodePort
status:
  loadBalancer: {}
